"""create user

Revision ID: 79f4be30ace8
Revises: cd1e31b150e2
Create Date: 2021-01-16 22:26:38.377133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f4be30ace8'
down_revision = 'cd1e31b150e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_delete', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_delete')
    # ### end Alembic commands ###
